package com.vibrent.aftership.enums;

public enum ExternalEventEnum {
    AFTER_SHIP_TRACKING_RESPONSE_SENT,
    AFTER_SHIP_TRACKING_REQUEST,
    AFTER_SHIP_GET_TRACKING,
    FULFILLMENT_TRACK_DELIVERY_RESPONSE_SENT,
    FULFILLMENT_TRACK_DELIVERY_REQUEST_RECEIVED
}
